name: Nostr issue action
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"
      - name: Publish Issue to Nostr
        uses: ChristianChiarulli/nostr-issues-test@v0.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          nsec: ${{ secrets.NSEC }}
          kind: "1"
          tags: "[]"
          relays: '["wss://nos.lol", "wss://relay.damus.io",]'
